src/accounts/urls.py
from django.conf.urls import url
from .views import (
        login_view, logout_view, register_view
    )

urlpatterns = [
    url(r'^login/$', login_view, name='login'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^register/$', register_view, name='register'),
]

src/blog/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comments/', include('comments.urls', namespace='comments')),
    url(r'^posts/', include('posts.urls', namespace='posts')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^api/posts/', include('posts.api.urls', namespace='posts_api')),
    url(r'^api/comments/', include('comments.api.urls', namespace='comments_api')),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/api/urls.py
from django.conf.urls import url
from .views import (
    PostCreateApiView,
    PostDeleteApiView,
    PostDetailApiView,
    PostListApiView,
    PostUpdateApiView,
)

urlpatterns = [
    url(r'^$', PostListApiView.as_view(), name='list'),
    url(r'^create/$', PostCreateApiView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailApiView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', PostUpdateApiView.as_view(), name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteApiView.as_view(), name='delete'),
]

src/posts/urls.py
from django.conf.urls import url
from .views import (
    post_create,
    post_delete,
    post_detail,
    post_list,
    post_update,
    )

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[-\w]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[-\w]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[-\w]+)/delete/$', post_delete, name='delete'),
]

src/posts/models.py
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify

from markdown_deux import markdown

from comments.models import Comment

from .utils import get_read_time


class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False, publish__lte=timezone.now())


def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=False, null=False)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True, max_length=200)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True, width_field="height_field",
                              height_field="width_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateTimeField(auto_now=False, auto_now_add=False)
    read_time = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return "{}".format(self.title)

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

    def get_markdown(self):
        return mark_safe(markdown(self.content))

    @property
    def comments(self):
        return Comment.objects.filter_by_instance(self)

    @property
    def get_content_type(self):
        return ContentType.objects.get_for_model(self.__class__)

    class Meta:
        ordering = ["-timestamp", "-updated"]


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    instance.slug = create_slug(instance)

    if instance.content:
        instance.read_time = get_read_time(markdown(instance.content))


def create_slug(instance, new_slug=None):
    if instance.slug:
        return instance.slug
    slug = slugify(instance.title)
    if new_slug:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()

    if exists:
        new_slug = "{}-{}".format(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms
from .models import Post

from pagedown.widgets import PagedownWidget


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget)

    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'draft',
            'publish',
        ]

src/posts/api/views.py
from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)
from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    RetrieveUpdateAPIView,
    RetrieveAPIView
)

from rest_framework.permissions import (
    AllowAny,
    IsAuthenticated,
    IsAdminUser,
    IsAuthenticatedOrReadOnly,
)

from ..models import Post
from .serializers import (
    PostCreateUpdateSerializer,
    PostListSerializer,
    PostDetailSerializer
)
from .pagination import PostLimitOffsetPagination, PostPageNumberPagination

from .permissions import IsOwnerOrReadOnly


class PostCreateApiView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)


class PostDetailApiView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = []

    lookup_field = 'slug'


class PostDeleteApiView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

    lookup_field = 'slug'


class PostListApiView(ListAPIView):
    queryset = Post.objects.all()
    serializer_class = PostListSerializer
    permission_classes = []
    filter_backends = [SearchFilter]
    search_fields = ['title', 'content', 'user__first_name', 'user__last_name']
    pagination_class = PostPageNumberPagination


class PostUpdateApiView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [IsAuthenticated, IsOwnerOrReadOnly]

    lookup_field = 'slug'

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

src/posts/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import PostForm
from .models import Post

from comments.models import Comment
from comments.forms import CommentForm


def post_list(request):
    posts = Post.objects.active()
    if check_authenticated(request):
        posts = Post.objects.all()

    query = request.GET.get("q")
    posts = posts.filter(Q(title__icontains=query) |
                         Q(content__icontains=query) |
                         Q(user__first_name__icontains=query) |
                         Q(user__last_name__icontains=query)).distinct() if query else posts

    page_request_var = "page"
    paginated_posts = paginated_res(request, posts, 5, page_request_var)
    ctx = {
        "instance": paginated_posts,
        "page_request_var": "page",
        "now": timezone.now()
    }
    return render(request, "posts/index.html", ctx)


def post_detail(request, slug=None):
    obj = get_object_or_404(Post, slug=slug)
    draft = obj.draft or obj.publish > timezone.now()
    if draft:
        check_authenticated_with_404(request)

    initial_data = {
        'content_type': obj.get_content_type,
        'object_id': obj.id,
    }
    comment_form = CommentForm(request.POST or None, initial=initial_data)

    if comment_form.is_valid() and request.user.is_authenticated():
        c_type = comment_form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        object_id = comment_form.cleaned_data.get("object_id")
        try:
            parent_id = int(request.POST.get("parent_id"))
        except:
            parent_id = None
        parent_obj = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            parent_obj = parent_qs.first() if parent_qs.exists() else None

        content = comment_form.cleaned_data.get("content")

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=object_id,
            content=content,
            parent=parent_obj
        )

        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = Comment.objects.filter_by_instance(obj)
    ctx = {
        'instance': obj,
        'draft': draft,
        'comments': comments,
        'comment_form': comment_form,
    }
    return render(request, "posts/post_detail.html", ctx)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Post created successfully", extra_tags='')
        return HttpResponseRedirect(instance.get_absolute_url())
    ctx = {
        'form': form,
        'label': "Create Post"
    }
    return render(request, "posts/post_form.html", ctx)


@login_required
def post_update(request, slug=None):
    obj = get_object_or_404(Post, slug=slug)

    form = PostForm(request.POST or None, request.FILES or None, instance=obj)

    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Post updated successfully", extra_tags='')
        return HttpResponseRedirect(instance.get_absolute_url())

    ctx = {
        'title': obj.title,
        'content': obj.content,
        'form': form,
        'label': "Update Post"
    }
    return render(request, "posts/post_form.html", ctx)


@login_required
def post_delete(request, slug=None):
    obj = get_object_or_404(Post, slug=slug)
    if obj:
        obj.delete()
        messages.success(request, "Post deleted successfully", extra_tags='')
        return redirect("posts:list")
    return redirect("posts:list")


def paginated_res(request, obj, per_page, page_request_var="page"):
    paginator = Paginator(obj, per_page=per_page)
    page = request.GET.get(page_request_var) or 1
    try:
        res = paginator.page(page)
    except PageNotAnInteger:
        res = paginator.page(1)
    except EmptyPage:
        res = paginator.page(paginator.num_pages)
    return res or None


def check_authenticated(request):
    return False if not request.user.is_staff or not request.user.is_superuser else True


def check_authenticated_with_404(request):
    if not check_authenticated(request):
        raise Http404
    return True

src/templates/posts/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href='{% static "vendor/css/bootstrap.min.css" %}'>
    <link rel="stylesheet" href='{% static "vendor/css/bootstrap-theme.min.css" %}'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block head_extra %}{% endblock %}
    <link rel="stylesheet" href='{% static "css/base.css" %}'>


</head>
<body>
<div id="fb-root"></div>
<script>(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s);
    js.id = id;
    js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.11';
    fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'posts:list' %}">Home</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <!--<li class="active"><a href="{% url 'posts:create' %}">Create Post <span class="sr-only">(current)</span></a></li>-->
                    <!--<li><a href="#">Link</a></li>-->
                    <!--<li class="dropdown">-->
                        <!--<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"-->
                           <!--aria-expanded="false">Dropdown <span class="caret"></span></a>-->
                        <!--<ul class="dropdown-menu">-->
                            <!--<li><a href="#">Action</a></li>-->
                            <!--<li><a href="#">Another action</a></li>-->
                            <!--<li><a href="#">Something else here</a></li>-->
                            <!--<li role="separator" class="divider"></li>-->
                            <!--<li><a href="#">Separated link</a></li>-->
                            <!--<li role="separator" class="divider"></li>-->
                            <!--<li><a href="#">One more separated link</a></li>-->
                        <!--</ul>-->
                    <!--</li>-->
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% block search %}{% endblock %}
                    <!--<li><a href="#">Link</a></li>-->
                    <li class="dropdown">
                        <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            {% if request.user.is_authenticated %}
                            {% if request.user.get_full_name %}
                            {{request.user.get_full_name}}
                            {% elif request.user.username %}
                            {{request.user.username}}
                            {% endif %}
                            {% else %}
                            Guest
                            {% endif %}
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> <span
                                class="glyphicon-class"></span>
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            {% if not request.user.is_authenticated %}
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'accounts:login' %}">Sign in</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'accounts:register' %}">Sign up</a></li>
                            <li role="separator" class="divider"></li>

                            {% else %}
                            <li role="separator" class="divider"></li>
                            <li><a href="#">Profile <small>coming soon</small></a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            <li role="separator" class="divider"></li>

                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
    </nav>
</div>
{% include "common/messages.html" %}
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src='{% static "vendor/jquery-3.2.1.min.js" %}'></script>
<script src='{% static "vendor/js/bootstrap.min.js" %}'></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.12/marked.min.js"></script>

<script type="text/javascript">

    $(document).ready(function () {
        $(".content-markdown").each(function () {
            var content = $(this).text();
            var markedContent = marked(content);
            $(this).html(markedContent)
        });

        $(".post-detail-item img").each(function () {
            $(this).addClass("img-responsive")
        });


        // preview-content
        var contentInput = $("#id_content");

        function setContent(value) {
            var markedContent = marked(value);
            $("#preview-content").html(marked(markedContent));
            $("#preview-content img").each(function () {
                $(this).addClass("img-responsive")
            })
        }

        setContent(contentInput.val());
        contentInput.keyup(function () {
            var newContent = $(this).val();
            setContent(newContent);
        });

        // preview-title
        var titleInput = $("#id_title");


        function setTitle(value) {
            $("#preview-title").text(value);
        }

        setTitle(titleInput.val());
        titleInput.keyup(function () {
            var newTitle = $(this).val();
            setTitle(newTitle);
        });

        $(".comment-reply-btn").click(function (event) {
            event.preventDefault();
            $(this).parent().next(".comment-reply").fadeToggle();
        });
    })

</script>

</body>
</html>

src/templates/posts/index.html
{% extends "posts/base.html" %}

{% block title %}all posts{% endblock %}
{% block search %}
<form class="navbar-form navbar-left" method="GET">
    <div class="input-group">
        <input type="text" name="q" class="form-control" placeholder="Search Posts" aria-describedby="basic-addon2">
        <span class="input-group-btn">
        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
        </span>
    </div>
</form>{% endblock %}
{% block content %}
{% if request.user.is_authenticated %}

    <a href="{% url 'posts:create' %}" class="btn btn-success">New post</a>

{% endif %}
<p></p>
{% if request.GET.q %}
<p>Showing results for : <b>{{ request.GET.q }}</b></p>
{% endif %}
<div class="row">
    {% if not instance %}
    <h3>Sorry, no posts available at the moment !!</h3>
    {% endif %}
    {% for obj in instance %}
    <div class="row">
        <div class="col-sm-12">
            <div class="thumbnail">
                {% if obj.image %}
                <img src="{{ obj.image.url }}" alt="" class="img-responsive">
                {% endif %}
                <div class="caption">
                    <a href='{{ obj.get_absolute_url }}'><h3>{% if obj.draft or obj.publish > now %}<font color="red">Draft </font>
                        {% endif %}{{ obj.title }}</h3>
                    </a>
                    <div class="post-detail-item">{{ obj.get_markdown|truncatewords_html:120 }}</div>
                    <p></p>
                    {% if obj.user.get_full_name %}
                    <p><b>Author:</b> {{ obj.user.get_full_name }}</p>
                    {% else %}
                    <p><b>Author:</b> {{ obj.user.username }}</p>
                    {% endif %}
                    <b>Published : </b>
                    <small>{{ obj.publish | timesince }} ago</small>

                </div>
            </div>
        </div>
    </div>
    <hr>
    {% endfor %}
    {% include "common/pagination.html" %}
</div>
{% endblock %}

src/templates/posts/post_detail.html
{% extends "posts/base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}
{% block title %}{{ title }}{% endblock %}

{% block content %}

<div class="row">
    <br>
    <h1>{% if draft %}<font color="red">Draft </font>{% endif %}{{ instance.title }}</h1>

    <small>{% if instance.read_time <= 1 %} Less than 1 minute {% else %}
        {{ instance.read_time }} minutes {%endif %} <b>read. </b>
    </small>
    <br><br>


    {% if instance.image %}
    <img src="{{ instance.image.url }}" alt="" class="img-responsive">
    {% endif %}
    <div class="post-detail-item">{{ instance.get_markdown }}</div>
    <p></p>
    {% if instance.user.get_full_name %}
    <p><b>Author:</b> {{ instance.user.get_full_name }}</p>
    {% else %}
    <p><b>Author:</b> {{ instance.user.username }}</p>
    {% endif %}
    <b>Published : </b>
    <small>{{ instance.publish | timesince }} ago</small>
    <br>

    <p>
    <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="standard"
         data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
    </p>

    <a href="https://twitter.com/home?status={{ instance.content|truncatewords:100|urlify }}%20{{ request.build_absolute_uri }}">
        Twitter
    </a>

    <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>
        Google Plus
    </a>

    <a href="https://www.linkedin.com/shareArticle?mini=true&url={{ request.build_absolute_uri }}&title={{ instance.title | urlify }}&summary={{ instance.content | urlify }}&source={{ request.build_absolute_uri }}">
        Linkedin
    </a>

    <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ instance.title | urlify }}">Share
        Reddit
    </a>

    <hr>
    <p class="lead">Comments</p>
    {% if request.user.is_authenticated %}
    <div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input class="btn btn-success" type="submit" value="Post comment">
        </form>
        <hr>
    </div>
    {% else %}
    <p>
        <a href="{% url 'accounts:login' %}?next={{instance.get_absolute_url}}" class="btn btn-success">Sign in to post comments</a>
    </p>
    {% endif %}
    {% for comment in comments %}
    <div>
        <blockquote>
            <p>{{ comment.content }}</p>
            <small><b>{{ comment.user }}</b> {{comment.timestamp|timesince}} ago | {% if comment.children.count > 1 %}
                {{comment.children.count }} Comments {% elif comment.children.count == 1%} {{ comment.children.count }}
                Comment {%else %} 0 Comments {% endif %} {% if request.user.is_authenticated %}
                | <a class="comment-reply-btn"
                     href="#">Reply</a>
                {% endif %}
                | <a class=""
                     href="{{ comment.get_absolute_url }}">Thread</a>

            </small>
            <div class="comment-reply" style="display: none">
                {% for reply in comment.children %}
                <blockquote>
                    <p>{{ reply.content }}</p>
                    <small><b>{{ reply.user }}</b> {{reply.timestamp|timesince}} ago</small>
                </blockquote>

                {% endfor %}

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ comment_form|crispy }}
                    <input type="hidden" name="parent_id" value="{{ comment.id }}">
                    <input class="btn btn-default" type="submit" value="Reply">
                </form>

            </div>
        </blockquote>
        <hr>
    </div>
    {% endfor %}
</div>
{% endblock %}

src/templates/posts/post_form.html
{% extends "posts/base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %}
{{ form.media }}
{% endblock %}

{% block content %}
<div class="col-sm-6">
    <h5>Preview</h5>

    <div class="content-preview">
        <h1 id="preview-title"></h1>
        <hr>
        <p id="preview-content"></p>
    </div>
</div>
<div class="col-sm-6">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="{{ label }}">
        <a href="{% url 'posts:list' %}" class="btn btn-danger">cancel</a>
    </form>
</div>
{% endblock %}